# Generated by Django 5.0.2 on 2024-03-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='next_of_kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Emp_code',
            new_name='emp_code',
        ),
    ]
